# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Libiho
email: andreas.baak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Linux-based inividual photobooth (libipho).
baseurl: "/libipho" # the subpath of your site, e.g. /blog
url: "http://andreasbaak.github.io" # the base hostname & protocol for your site
imgurl: "/libipho/images" # the subpath where the images are hosted
github_username:  andreasbaak

# Build settings
markdown: kramdown
